//town
export const FETCH_TOWN_PENDING = 'FETCH_TOWN_PENDING';
export const FETCH_TOWN_SUCCESS = 'FETCH_TOWN_SUCCESS';
export const FETCH_TOWN_ERROR = 'FETCH_TOWN_ERROR';

//filters
export const SET_AGE_FILTER = 'SET_AGE_FILTER';
export const SET_AGE_MIN = 'SET_AGE_MIN';
export const SET_AGE_MAX = 'SET_AGE_MAX';
export const SET_AGE_RANGE = 'SET_AGE_RANGE';
export const SET_HEIGHT_FILTER = 'SET_HEIGHT_FILTER';
export const SET_HEIGHT_MIN = 'SET_HEIGHT_MIN';
export const SET_HEIGHT_MAX = 'SET_HEIGHT_MAX';
export const SET_HEIGHT_RANGE = 'SET_HEIGHT_RANGE';
export const SET_WEIGHT_FILTER = 'SET_WEIGHT_FILTER';
export const SET_WEIGHT_MIN = 'SET_WEIGHT_MIN';
export const SET_WEIGHT_MAX = 'SET_WEIGHT_MAX';
export const SET_WEIGHT_RANGE = 'SET_WEIGHT_RANGE';
export const ADD_HAIR_COLOR_FILTER = 'ADD_HAIR_COLOR_FILTER';
export const DELETE_HAIR_COLOR_FILTER = 'DELETE_HAIR_COLOR_FILTER';
export const CLEAR_HAIR_COLORS_FILTER = 'CLEAR_HAIR_COLORS_FILTER';
